[package]
name = "microvm-vz"
description = "Virtualization.framework bindings for microvm"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
objc2.workspace = true
objc2-foundation.workspace = true
objc2-virtualization.workspace = true
block2.workspace = true
thiserror.workspace = true
tracing.workspace = true
tokio.workspace = true
uuid.workspace = true
