import { buildSync } from "esbuild";
import { readdirSync, existsSync } from "node:fs";
import { join } from "node:path";

const actionsDir = ".github/actions";

for (const name of readdirSync(actionsDir)) {
	const entry = join(actionsDir, name, "src", "index.ts");
	if (!existsSync(entry)) continue;

	buildSync({
		entryPoints: [entry],
		bundle: true,
		platform: "node",
		target: "node24",
		outfile: join(actionsDir, name, "dist", "index.js"),
		format: "esm",
		banner: { js: "// @generated by esbuild. Do not edit by hand." },
	});

	console.log(`bundled ${name}`);
}
