// @generated by Hollywood. Do not edit by hand.

import { runGitHubAction } from "@dedalus-labs/hollywood/action-runtime";
import { publishCrates } from "../../../../gha/publish.ts";

void runGitHubAction(publishCrates);
